import { UserData, Connection, ProductType, ConnectionType, ConsumptionDataPoint, ConnectionStatus } from './types';

const generateRandomConsumption = (days: number, maxUsage: number, startDate: Date = new Date()): ConsumptionDataPoint[] => {
  const data: ConsumptionDataPoint[] = [];
  for (let i = days - 1; i >= 0; i--) {
    const date = new Date(startDate);
    date.setDate(startDate.getDate() - i);
    data.push({
      date: date.toISOString().split('T')[0],
      usage: parseFloat((Math.random() * maxUsage).toFixed(2)),
    });
  }
  return data;
};

export const allMockConnections: Connection[] = [
  {
    id: 'conn-01',
    product: ProductType.WATER,
    status: ConnectionStatus.ACTIVE,
    client: "Gemeente Dordrecht",
    department: "Vastgoed",
    connectionName: "Project Oekraine-Crown...",
    ean: '123000000001000150',
    address: 'Spuiboulevard 314',
    city: 'Dordrecht',
    postalCode: '3311 GR',
    country: 'Netherlands',
    latitude: 51.813,
    longitude: 4.665,
    connectionType: ConnectionType.LARGE,
    meters: [{ id: 'meter-w-01', type: ProductType.WATER, meterType: 'Smart', registrationReading: 6500.00, lastReading: 7890.12, lastReadingDate: new Date().toISOString().split('T')[0], unit: 'm\u00b3' }],
    consumption: generateRandomConsumption(30, 8),
    supplierInfo: { name: 'Vitens', startDate: '2020-01-15', endDate: '2025-01-14', contact: '0800-0359' },
    networkOperatorInfo: { name: 'Oasen', contact: '0182-593530' },
    technicalData: { capacity: 'DN 40', physicalStatus: 'In use' },
    notes: [{ text: 'Initial notes for the water connection at Spuiboulevard.', user: 'System', date: '2023-10-26T10:00:00Z' }],
    editHistory: [],
  },
  {
    id: 'conn-02',
    product: ProductType.ELEKTRA,
    status: ConnectionStatus.ACTIVE,
    client: "Gemeente Dordrecht",
    department: "Gemalen",
    connectionName: "Pomp 1116",
    ean: '871689290600869078',
    address: 'Abeelstraat 85 116-lamel',
    city: 'Dordrecht',
    postalCode: '3329 AC',
    country: 'Netherlands',
    latitude: 51.78,
    longitude: 4.64,
    connectionType: ConnectionType.LARGE,
    meters: [{ id: 'meter-e-01', type: ProductType.ELEKTRA, meterType: 'Smart', registrationReading: 10000.00, lastReading: 12345.67, lastReadingDate: new Date().toISOString().split('T')[0], unit: 'kWh' }],
    consumption: generateRandomConsumption(30, 15),
    supplierInfo: { name: 'Eneco', startDate: '2021-06-01', endDate: '2024-05-31', contact: '088-8955955' },
    networkOperatorInfo: { name: 'Stedin', contact: '088-8963963' },
    technicalData: { capacity: '3x80 A', physicalStatus: 'In use' },
    editHistory: [],
  },
  {
    id: 'conn-13',
    product: ProductType.GAS,
    status: ConnectionStatus.ACTIVE,
    client: "Drechtsteden Reiniging",
    department: "Operations",
    connectionName: "Depot Heating",
    ean: '871689200000000013',
    address: 'Baanhoekweg 38',
    city: 'Sliedrecht',
    postalCode: '3361 GE',
    country: 'Netherlands',
    latitude: 51.822,
    longitude: 4.757,
    connectionType: ConnectionType.LARGE,
    meters: [{ id: 'meter-g-10', type: ProductType.GAS, meterType: 'Smart', registrationReading: 50000, lastReading: 54321, lastReadingDate: new Date().toISOString().split('T')[0], unit: 'm\u00b3' }],
    consumption: generateRandomConsumption(30, 80),
    supplierInfo: { name: 'Vattenfall', startDate: '2022-01-01', endDate: '2025-01-01', contact: '020 892 0250' },
    networkOperatorInfo: { name: 'Stedin', contact: '088-8963963' },
    technicalData: { capacity: 'G25', physicalStatus: 'In use' },
    editHistory: [],
  },
  {
    id: 'conn-04',
    product: ProductType.ELEKTRA,
    status: ConnectionStatus.ACTIVE,
    client: "Energy Corp",
    department: "Headquarters",
    connectionName: "HQ Main Power",
    ean: '871689213001225717',
    address: 'Zuidplein 112',
    city: 'Rotterdam',
    postalCode: '3083 CW',
    country: 'Netherlands',
    latitude: 51.888,
    longitude: 4.489,
    connectionType: ConnectionType.LARGE,
    meters: [
      { id: 'meter-e-03', type: ProductType.ELEKTRA, meterType: 'Smart', registrationReading: 20000.00, lastReading: 23456.78, lastReadingDate: new Date().toISOString().split('T')[0], unit: 'kWh' },
      { id: 'meter-g-03', type: ProductType.GAS, meterType: 'Smart', registrationReading: 8000.00, lastReading: 9876.54, lastReadingDate: new Date().toISOString().split('T')[0], unit: 'm\u00b3' },
    ],
    consumption: generateRandomConsumption(30, 120),
    supplierInfo: { name: 'Eneco', startDate: '2022-02-10', endDate: '2025-02-09', contact: '088-8955955' },
    networkOperatorInfo: { name: 'Stedin', contact: '088-8963963' },
    technicalData: { capacity: '3x63 A', physicalStatus: 'In use' },
    editHistory: [],
  },
  {
    id: 'conn-14',
    product: ProductType.ELEKTRA,
    status: ConnectionStatus.ACTIVE,
    client: "Energy Corp Germany",
    department: "Industrial",
    connectionName: "Frankfurt Factory Power",
    ean: '998877665544332211',
    address: 'Mainzer Landstraße 200',
    city: 'Frankfurt',
    postalCode: '60327',
    country: 'Germany',
    latitude: 50.107,
    longitude: 8.652,
    connectionType: ConnectionType.LARGE,
    meters: [{ id: 'meter-e-14', type: ProductType.ELEKTRA, meterType: 'Smart', registrationReading: 25000.00, lastReading: 28456.78, lastReadingDate: new Date().toISOString().split('T')[0], unit: 'kWh' }],
    consumption: generateRandomConsumption(30, 130),
    supplierInfo: { name: 'E.ON', startDate: '2022-02-10', endDate: '2025-02-09', contact: '+49 871 95386200' },
    networkOperatorInfo: { name: 'TenneT', contact: '+49 921 50740-0' },
    technicalData: { capacity: '3x80 A', physicalStatus: 'In use' },
    editHistory: [],
  },
  {
    id: 'conn-03',
    product: ProductType.ELEKTRA,
    status: ConnectionStatus.INACTIVE,
    client: "Energy Corp Benelux",
    department: "National Grids",
    connectionName: "Substation Brussels",
    ean: '871689206019908017',
    address: 'Rue de la Loi 16',
    city: 'Brussels',
    postalCode: '1000',
    country: 'Belgium',
    latitude: 50.845,
    longitude: 4.37,
    connectionType: ConnectionType.SMALL,
    meters: [{ id: 'meter-e-02', type: ProductType.ELEKTRA, meterType: 'Conventional', registrationReading: 7000.00, lastReading: 8765.43, lastReadingDate: new Date().toISOString().split('T')[0], unit: 'kWh' }],
    consumption: generateRandomConsumption(30, 25),
    supplierInfo: { name: 'Engie', startDate: '2019-08-20', endDate: '2022-08-19', contact: '+32 2 518 61 11' },
    networkOperatorInfo: { name: 'Elia', contact: '+32 2 546 70 11' },
    technicalData: { capacity: '3x25 A', physicalStatus: 'Disconnected' },
    editHistory: [],
  },
  {
    id: 'conn-08',
    product: ProductType.GAS,
    status: ConnectionStatus.ACTIVE,
    client: "Energy Corp Benelux",
    department: "Residential",
    connectionName: "Antwerp Housing Gas Line",
    ean: '871689200000000008',
    address: 'Grote Markt 1',
    city: 'Antwerp',
    postalCode: '2000',
    country: 'Belgium',
    latitude: 51.221,
    longitude: 4.401,
    connectionType: ConnectionType.SMALL,
    meters: [{ id: 'meter-g-04', type: ProductType.GAS, meterType: 'Smart', registrationReading: 1000.00, lastReading: 1122.33, lastReadingDate: new Date().toISOString().split('T')[0], unit: 'm\u00b3' }],
    consumption: generateRandomConsumption(30, 15),
    supplierInfo: { name: 'Luminus', startDate: '2022-07-20', endDate: '2025-07-19', contact: '+32 2 302 20 00' },
    networkOperatorInfo: { name: 'Fluvius', contact: '+32 78 35 35 34' },
    technicalData: { capacity: 'G6', physicalStatus: 'In use' },
    editHistory: [],
  }
];

const user1Clients = ['Gemeente Dordrecht', 'Drechtsteden Reiniging'];
const user2Clients = ['Energy Corp', 'Energy Corp Benelux', 'Energy Corp Germany'];

export const mockUsers: UserData[] = [
  {
    id: 'user-001',
    name: 'Alex Doe',
    email: '1@1.com',
    accessibleClients: user1Clients,
    connections: allMockConnections.filter(c => user1Clients.includes(c.client)),
  },
  {
    id: 'user-002',
    name: 'Jane Smith',
    email: '2@2.com',
    accessibleClients: user2Clients,
    connections: allMockConnections.filter(c => user2Clients.includes(c.client)),
  }
];
